---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wwsz.
--- DateTime: 2024/9/6 上午11:32
---
--参数列表,用户id，秒杀券id,订单id
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]
--定义库存key
local stockKey = "seckill:stock:" .. voucherId
--定义订单key
local orderKey = "seckill:order:" .. voucherId
--读取库存
local stock =redis.call("get", stockKey)
--判断库存
if(tonumber(stock) <= 0) then
    return 1
end
--判断用户是否下单过
local orderif = redis.call("sismember", orderKey, userId)
if orderif == 1 then --存在说明是重复下单，不允许
    return 2
end
--扣减库存incrby stockKey -1
redis.call("incrby", stockKey, -1)
--正式下单，创建库存信息
redis.call("sadd", orderKey, userId)
--发送消息进入消息队列 xadd stream.orders(队列名) *（redis自行生成id） key1 value1 key2 value2...
redis.call("xadd", "stream.orders", "*", "userId", userId, "voucherId", voucherId, "id", orderId)
return 0