---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wwsz.
--- DateTime: 2024/9/4 下午9:56
---
--获取锁中的线程标识 get key
local id = redis.call("get", KEYS[1])
--比较线程标识和锁标识是否一致
if(id == ARGV[1]) then
    --释放锁
    return redis.call("del", KEYS[1])
end
return 0